language: ruby
sudo: false
dist: trusty

addons:
  chrome: stable
cache:
  bundler: true

before_install:
  - gem update --system 3.0.6
  - gem install bundler
  - gem install chromedriver-helper -v 1.2.0
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} --without production

rvm:
  - 2.5.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test'
  # Travis should check every minor version in a range of supported versions, because
  # rails does not follow sem-ver conventions, see http://guides.rubyonrails.org/maintenance_policy.html
  # It should be sufficient to test only the latest of the patch versions for a minor version, they
  # should be compatible across patch versions (only bug fixes are released in patch versions).


script:
  - bundle exec rake ci

services:
  - redis-server
before_script:
  - jdk_switcher use oraclejdk8
  - bundle exec rubocop
  - sudo mount -o remount,size=32G /run/shm
  - chromedriver-update 73.0.3683.68
